#!/bin/bash

echo "Employee Management System - Database Setup"
echo "==========================================="
echo ""
echo "Please make sure Laragon is running before proceeding."
echo ""
echo "Steps to follow:"
echo "1. Open Laragon application"
echo "2. Click 'Start All' to start Apache and MySQL"
echo "3. Wait for services to start (green indicators)"
echo "4. Open http://localhost/phpmyadmin in your browser"
echo "5. Create a new database named 'employee_management'"
echo "6. After creating the database, run: php artisan migrate"
echo "7. Then run: php artisan db:seed --class=RoleAndPermissionSeeder"
echo "8. Finally run: php artisan db:seed --class=SuperAdminSeeder"
echo ""
echo "Alternatively, you can create the database via command line:"
echo "mysql -u root -p -e 'CREATE DATABASE employee_management;'"
echo ""
echo "Default login credentials for Super Admin:"
echo "Email: superadmin@company.com"
echo "Password: SuperAdmin@123"
